version: '3'
services:
  goworkspace:
    build:
      context: ./build/docker
      dockerfile: workspace.Dockerfile
    command: /bin/sleep infinity
    restart: unless-stopped
    volumes:
      - ./:/code/
    # environment:
    #   - test=test

  api:
    image: itsalex/alpine-reflex-with-golang:1.20.3-alpine3.17
    restart: unless-stopped
    working_dir: /code
    volumes:
      - ./:/code/
      - ../pdf-templates:/templates/
    ports:
      - 8080:8080
    command: reflex -r '\.go$' -s -- sh -c 'go mod download && go run /code/cmd/gibbon-pdf/main.go'
